//
//  Resolver.swift
//  Generated by dikitgen.
//

extension AppResolver {

    func resolveAPIClient() -> APIClient {
        return provideAPIClient()
    }

    func resolveViewController() -> ViewController {
        let apiClient = resolveAPIClient()
        return ViewController(dependency: .init(apiClient: apiClient))
    }

}

